name: Add Rules to Cloudflare Gateway
on:
  schedule:
    - cron: "15 15 * * 1,5"
  workflow_dispatch:
jobs:
  run:
    name: Cloudflare Gateway
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Keep alive 
        uses: gautamkrishnar/keepalive-workflow@v1

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          
      - name: Cloudflare Gateway Zero Trust 
        run: python -m src 
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_IDENTIFIER: ${{ secrets.CF_IDENTIFIER }}
          PYTHONDONTWRITEBYTECODE: 1
      
      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV
  
      - name: Commit filters
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'hosts'
          default_author: github_actor 
          message: 'Update: ${{ env.DATE }}'
          push: true
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
